FROM balenalib/%%BALENA_MACHINE_NAME%%-python:2-build

# pip install python deps from requirements.txt
# For caching until requirements.txt changes
COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY . /usr/src/app
WORKDIR /usr/src/app

RUN chromatron compile chaser.fx && \
    chromatron compile emergency.fx && \
    chromatron compile rainbow.fx && \
    chromatron compile lightning.fx

CMD ["python", "button-control.py"]